#include "../datacollection/hashTree/HashNode.h"
#include "../datacollection/hashTree/HashTree.h"
#include <iostream>
#include <string>

using namespace std;
namespace  fs =  std::filesystem;

typedef struct GardenTag_s {
    char *message;
    char *signature;
    long long timestamp;
    HashNode_s *root;
} GardenTag_s;

/**
 * class that holds the data to point to a commit of an Hashtree
 */
class GardenTag{

public:
    /**
     * Construct a GardenTag with the specified roo
     * @param tree the tree that the tag should point to
     * @param msg the message recorded by the user to explain the changed in the repo
     */
    GardenTag(HashTree *tree, string msg)
    {
        setRoot(tree->getRoot());
        value->timestamp = time(NULL);
        value->message = msg.data();
        generateSignature();
    };

    /**
     * gets the hashed signature generated by the tag
     * @return the hash of the tag
     */
    string getHash();
    /**
     * get the signature of the root of the HashTree
     * @return the signature of the root of the HashTree
     */
    string getRootHash();

    string getMessage();
    FolderNode* getRoot(){
        return new FolderNode(value->root);
    }

    GardenTag_s *getStructValue();

    operator GardenTag_s *() const {
        return  value;
    }


    private:
        GardenTag_s *value;

        void setRoot(FolderNode *root);
        void generateSignature();
};